owner: rollerozxa-org
repo: mt-uptime-status

sites:
  - name: minetest.net
    url: https://www.minetest.net
    maxResponseTime: 2000
  - name: content.minetest.net
    url: https://content.minetest.net
    maxResponseTime: 2000
  - name: forum.minetest.net
    url: https://forum.minetest.net
    maxResponseTime: 2000
  - name: servers.minetest.net
    url: https://servers.minetest.net
    maxResponseTime: 2000
  - name: wiki.minetest.net
    url: https://wiki.minetest.net/Main_Page
    maxResponseTime: 2000
  - name: dev.minetest.net
    url: https://dev.minetest.net/Main_Page
    maxResponseTime: 2000

status-website:
  cname: mtstatus.voxelmanip.se
  name: Minetest websites status
  introTitle: Minetest websites status
  introMessage: This status page tracks the uptime and status for Minetest websites.
  navbar:
    - title: Status
      href: /

i18n:
  footer: Powered by [Upptime](https://upptime.js.org)
